### ISSUE TITLE
treefactor-up is not refiling text in the same directory or one level higher

### ISSUE THREAD

**Issue by alex-a-soto** [cyberthal/treesort#2]
Thank you for creating this package and the time put into the documentation and theory behind imprecise inductive filing and using directories as a meta-outline. 

I've been using the package for the past few days, mostly using treefactor-throw to refile items to their respective directories. However, I've been running into an issue with treefactor-up. If you have an opportunity to look into this bug, I would greatly appreciate it. 

Thank you.

**Bug Description**
treefactor-up does not refile text/headings in the same directory or one level higher. If Inbox.org is not present, the first initial treefactor-up works as intended, but subsequent ones do not.

**Steps to Reproduce**
1. Go to a directory that contains an org-file
2. Open the org-file and select a heading
3. M-x treefactor-up the object heading to Inbox.org
4. Open Inbox.org
5. Verify the heading arrived.

**Actual Result:**
After running treefactor-up on a heading and open Inbox.org the heading is not present. The heading is not present in the same or one directory level higher.

If an Inbox.org is not present when running treefactor-up initially, a new Inbox.org is created, and the text is successfully is present.

**Expected Result:**
Text will go to an Inbox.org of the same directory level, or one
higher if already in an Inbox.org

**Build Version**
- GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-05-12

- Org mode version 9.4

Testing was done using emacs -Q

**Comment by cyberthal** [comment]
You're right, and this is a data-loss bug! I guess I'm going to have to write some tests to prevent this from happening again. Thank you for catching this. I don't know how much data I've lost this way. My inexperience is really showing here. I'll fix it ASAP.

**Comment by cyberthal** [comment]
Ok, I've reliably reproduced the bug. This only affects a particular use of treefactor-up that is a very rare part of my workflow:

in directory ~/foobar
create file ~/foobar/baz
add headings to it
run treefactor-up on all the headings
the first heading will correctly appear in ~/foobar/Inbox.org
  UNLESS Inbox.org already exists. then the heading will disappear silently
all subsequent headings will disappear silently.

**Comment by alex-a-soto** [comment]
@cyberthal Thank you for taking a look at the bug!

I've been experimenting with the package this week and I was looking to adopt it into my workflow and then I noticed the behavior you mentioned when I was trying to treefactor-up a heading to a different category/directory.

**Comment by cyberthal** [comment]
Thanks for catching it, man.

This bug also affects treefactor-refile a heading to a filename (not a directory) in Dired. Really bad. Also a rare part of my workflow.

The culprit is treefactor-insert-text-to-file-blind, which was missing a progn. Fix should be out soon.

**Comment by alex-a-soto** [comment]
Not a problem! Glad to help!

> The culprit is treefactor-insert-text-to-file-blind, which was missing a progn. Fix should be out soon.

That's great to hear! Looking forward to the fix and using the package further!

**Comment by cyberthal** [comment]
Fix released in v3.2.2
